In [2]:
import pandas as pd

In [4]:
# stack overflow developers data
df = pd.read_csv('data/survey_results_public.csv', index_col='Respondent') # sets unique index that we want in data
schema_df = pd.read_csv('data/survey_results_schema.csv', index_col='Column') #sets index to be column

In [5]:
pd.set_option('display.max_columns', 85) # so we can see all the columns
pd.set_option('display.max_rows', 85) # so we can see all the rows

In [6]:
df.head()

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [7]:
df.shape # this is an attribute so don't use ()

(88883, 84)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 88883 entries, 1 to 88863
Data columns (total 84 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   MainBranch              88331 non-null  object
 1   Hobbyist                88883 non-null  object
 2   OpenSourcer             88883 non-null  object
 3   OpenSource              86842 non-null  object
 4   Employment              87181 non-null  object
 5   Country                 88751 non-null  object
 6   Student                 87014 non-null  object
 7   EdLevel                 86390 non-null  object
 8   UndergradMajor          75614 non-null  object
 9   EduOther                84260 non-null  object
 10  OrgSize                 71791 non-null  object
 11  DevType                 81335 non-null  object
 12  YearsCode               87938 non-null  object
 13  Age1stCode              87634 non-null  object
 14  YearsCodePro            74331 non-null  object
 15  CareerSat               72847 non-null  object
 16  JobSat                  70988 non-null  object
 17  MgrIdiot                61159 non-null  object
 18  MgrMoney                61157 non-null  object
 19  MgrWant                 61232 non-null  object
 20  JobSeek                 80555 non-null  object
 21  LastHireDate            79854 non-null  object
 22  LastInt                 67155 non-null  object
 23  FizzBuzz                71344 non-null  object
 24  JobFactors              79371 non-null  object
 25  ResumeUpdate            77877 non-null  object
 26  CurrencySymbol          71392 non-null  object
 27  CurrencyDesc            71392 non-null  object
 28  CompTotal               55945 non-null  float64
 29  CompFreq                63268 non-null  object
 30  ConvertedComp           55823 non-null  float64
 31  WorkWeekHrs             64503 non-null  float64
 32  WorkPlan                68914 non-null  object
 33  WorkChallenge           68141 non-null  object
 34  WorkRemote              70284 non-null  object
 35  WorkLoc                 70055 non-null  object
 36  ImpSyn                  71779 non-null  object
 37  CodeRev                 70390 non-null  object
 38  CodeRevHrs              49790 non-null  float64
 39  UnitTests               62668 non-null  object
 40  PurchaseHow             61108 non-null  object
 41  PurchaseWhat            62029 non-null  object
 42  LanguageWorkedWith      87569 non-null  object
 43  LanguageDesireNextYear  84088 non-null  object
 44  DatabaseWorkedWith      76026 non-null  object
 45  DatabaseDesireNextYear  69147 non-null  object
 46  PlatformWorkedWith      80714 non-null  object
 47  PlatformDesireNextYear  77443 non-null  object
 48  WebFrameWorkedWith      65022 non-null  object
 49  WebFrameDesireNextYear  62944 non-null  object
 50  MiscTechWorkedWith      59586 non-null  object
 51  MiscTechDesireNextYear  64511 non-null  object
 52  DevEnviron              87317 non-null  object
 53  OpSys                   87851 non-null  object
 54  Containers              85366 non-null  object
 55  BlockchainOrg           48175 non-null  object
 56  BlockchainIs            60165 non-null  object
 57  BetterLife              86269 non-null  object
 58  ITperson                87141 non-null  object
 59  OffOn                   86663 non-null  object
 60  SocialMedia             84437 non-null  object
 61  Extraversion            87305 non-null  object
 62  ScreenName              80486 non-null  object
 63  SOVisit1st              83877 non-null  object
 64  SOVisitFreq             88263 non-null  object
 65  SOVisitTo               88086 non-null  object
 66  SOFindAnswer            87816 non-null  object
 67  SOTimeSaved             86344 non-null  object
 68  SOHowMuchTime           68378 non-null  object
 69  SOAccount               87828 non-null  object
 70  SOPartFreq              74692 non-null  object
 71  SOJobs                  88066 non-null  object
 72  EntTeams                87841 non-null  object
 73  SOComm                  88131 non-null  object
 74  WelcomeChange           85855 non-null  object
 75  SONewContent            69560 non-null  object
 76  Age                     79210 non-null  float64
 77  Gender                  85406 non-null  object
 78  Trans                   83607 non-null  object
 79  Sexuality               76147 non-null  object
 80  Ethnicity               76668 non-null  object
 81  Dependents              83059 non-null  object
 82  SurveyLength            86984 non-null  object
 83  SurveyEase              87081 non-null  object
dtypes: float64(5), object(79)
memory usage: 57.6+ MB

In [ ]:
schema_df #this gives us all the columns in the earlier df. This tells us what the column means

In [ ]:
# so now I can use .loc to see what the information for a particular category to find its meaning
schema_df.loc['Hobbyist']

In [ ]:
# what does MgrIdiot mean?
schema_df.loc['MgrIdiot', 'QuestionText']

In [ ]:
# sort alphabetically
schema_df.sort_index(ascending=True)

In [ ]:
#grab all responses for Hobbyist column
df['Hobbyist'].value_counts()

In [ ]:
# lets grab a specific row and column
df.loc[0] # gets all answers from one row
df.loc[0:3, 'Hobbyist':'Employment']

# Filtering

In [100]:
filt_high_salary = (df['ConvertedComp'] > 90000) & (df['Country'] == 'United States')

In [101]:
df.loc[filt_high_salary, ['Country', 'LanguageWorkedWith', 'ConvertedComp']]

,Country,LanguageWorkedWith,ConvertedComp
Respondent,,,
22,United States,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...,103000.0
26,United States,Bash/Shell/PowerShell;C++;C#;HTML/CSS;JavaScri...,114000.0
29,United States,Bash/Shell/PowerShell;JavaScript;SQL,100000.0
32,United States,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...,1100000.0
39,United States,C#;JavaScript;SQL;TypeScript,156000.0
...,...,...,...
88865,United States,HTML/CSS;JavaScript,120000.0
88874,United States,C++;Python;Scala;SQL,2000000.0
88876,United States,Bash/Shell/PowerShell;C#;HTML/CSS;Java;Python;...,180000.0
88877,United States,Bash/Shell/PowerShell;C;Clojure;HTML/CSS;Java;...,2000000.0
88878,United States,HTML/CSS;JavaScript;Scala;TypeScript,130000.0

In [102]:
countries = ['United States', 'France', 'Germany', 'United Kingdom', 'Canada']
filt = df['Country'].isin(countries)

In [107]:
df.loc[filt, 'Country']

Respondent
1        United Kingdom
4         United States
6                Canada
12               Canada
13        United States
              ...
85182            Canada
85642     United States
85961    United Kingdom
88282     United States
88377            Canada
Name: Country, Length: 38338, dtype: object

## Common Filtering Technique to get only people with python as a language

In [111]:
df['LanguageWorkedWith']

Respondent
1                          HTML/CSS;Java;JavaScript;Python
2                                      C++;HTML/CSS;Python
3                                                 HTML/CSS
4                                      C;C++;C#;Python;SQL
5              C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA
                               ...
88377                        HTML/CSS;JavaScript;Other(s):
88601                                                  NaN
88802                                                  NaN
88816                                                  NaN
88863    Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...
Name: LanguageWorkedWith, Length: 88883, dtype: object

In [112]:
# Does the string in this column .    contain python. Don't mess with null values
filt_python = df['LanguageWorkedWith'].str.contains('Python', na=False)

In [113]:
df.loc[filt_python,'LanguageWorkedWith' ]

Respondent
1                          HTML/CSS;Java;JavaScript;Python
2                                      C++;HTML/CSS;Python
4                                      C;C++;C#;Python;SQL
5              C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA
8        Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...
                               ...
84539    Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...
85738      Bash/Shell/PowerShell;C++;Python;Ruby;Other(s):
86566      Bash/Shell/PowerShell;HTML/CSS;Python;Other(s):
87739             C;C++;HTML/CSS;JavaScript;PHP;Python;SQL
88212                           HTML/CSS;JavaScript;Python
Name: LanguageWorkedWith, Length: 36443, dtype: object

## Start of New Dataframe for practice in changing index and accessing columns

In [77]:
people = {
    'first': ['Andre', 'Rahel', 'Kris', 'Lauren', 'Lisa', 'Adrienne', 'Kelly', 'Kelly'],
    'last': ['Williams', 'Zeleke', 'Kellems', 'Williams', 'Hancock', 'Williams', 'Puddy', 'Matthew'],
    'age': [19, 28, 27, 23, 54, 19, 35, 23],
    'email': ['awjrs22@gmail.com', 'rzeleke@gmail.com', 'kriswework@gmail.com', 'missdimples@gmail.com', 'mrs_lisa@yahoo.com', 'adrwil@gmail.com','kellyp@gmail.com', 'kmatthew@yahoo.com']
}

In [78]:
data = pd.DataFrame(people)

In [79]:
data

      first      last  age                  email
0     Andre  Williams   19      awjrs22@gmail.com
1     Rahel    Zeleke   28      rzeleke@gmail.com
2      Kris   Kellems   27   kriswework@gmail.com
3    Lauren  Williams   23  missdimples@gmail.com
4      Lisa   Hancock   54     mrs_lisa@yahoo.com
5  Adrienne  Williams   19       adrwil@gmail.com
6     Kelly     Puddy   35       kellyp@gmail.com
7     Kelly   Matthew   23     kmatthew@yahoo.com

In [80]:
data['email']

0        awjrs22@gmail.com
1        rzeleke@gmail.com
2     kriswework@gmail.com
3    missdimples@gmail.com
4       mrs_lisa@yahoo.com
5         adrwil@gmail.com
6         kellyp@gmail.com
7       kmatthew@yahoo.com
Name: email, dtype: object

In [81]:
data.set_index('email', inplace=True)

In [82]:
data

                          first      last  age
email
awjrs22@gmail.com         Andre  Williams   19
rzeleke@gmail.com         Rahel    Zeleke   28
kriswework@gmail.com       Kris   Kellems   27
missdimples@gmail.com    Lauren  Williams   23
mrs_lisa@yahoo.com         Lisa   Hancock   54
adrwil@gmail.com       Adrienne  Williams   19
kellyp@gmail.com          Kelly     Puddy   35
kmatthew@yahoo.com        Kelly   Matthew   23

In [83]:
data.index

Index(['awjrs22@gmail.com', 'rzeleke@gmail.com', 'kriswework@gmail.com',
       'missdimples@gmail.com', 'mrs_lisa@yahoo.com', 'adrwil@gmail.com',
       'kellyp@gmail.com', 'kmatthew@yahoo.com'],
      dtype='object', name='email')

In [84]:
data.loc['awjrs22@gmail.com']

first       Andre
last     Williams
age            19
Name: awjrs22@gmail.com, dtype: object

In [85]:
data.iloc[0]

first       Andre
last     Williams
age            19
Name: awjrs22@gmail.com, dtype: object

In [86]:
data.reset_index(inplace=True)
data

                   email     first      last  age
0      awjrs22@gmail.com     Andre  Williams   19
1      rzeleke@gmail.com     Rahel    Zeleke   28
2   kriswework@gmail.com      Kris   Kellems   27
3  missdimples@gmail.com    Lauren  Williams   23
4     mrs_lisa@yahoo.com      Lisa   Hancock   54
5       adrwil@gmail.com  Adrienne  Williams   19
6       kellyp@gmail.com     Kelly     Puddy   35
7     kmatthew@yahoo.com     Kelly   Matthew   23

## Filtering

In [87]:
filt = data['last'] == 'Williams'

In [88]:
data[filt]

                   email     first      last  age
0      awjrs22@gmail.com     Andre  Williams   19
3  missdimples@gmail.com    Lauren  Williams   23
5       adrwil@gmail.com  Adrienne  Williams   19

## Or

In [89]:
data.loc[filt, 'email'] # first values is rows and 2nd is columns

0        awjrs22@gmail.com
3    missdimples@gmail.com
5         adrwil@gmail.com
Name: email, dtype: object

## Lets say we want the last name williams and first name lauren

In [90]:
filts = (data['last'] == 'Williams') & (data['first'] == 'Lauren')

In [91]:
data.loc[filts]

                   email   first      last  age
3  missdimples@gmail.com  Lauren  Williams   23

## Lets say last name is williams or first name is kris

In [92]:
new = (data['last'] == 'Williams') | (data['first'] == 'Kris')

In [93]:
data.loc[new, 'email']

0        awjrs22@gmail.com
2     kriswework@gmail.com
3    missdimples@gmail.com
5         adrwil@gmail.com
Name: email, dtype: object

## Grab Opposite of Filter

In [94]:
data.loc[~new, 'email']

1     rzeleke@gmail.com
4    mrs_lisa@yahoo.com
6      kellyp@gmail.com
7    kmatthew@yahoo.com
Name: email, dtype: object

## Done with Created Dataframe